---
title: "Assignment1"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(gridExtra)
motorcycle <- read.table(
  "~/Dropbox/Uni/Regression/Assignment/motorcycle.txt", 
  header = TRUE,
  colClasses = c("numeric", "factor", "factor", "factor", "numeric", 
                 "factor", "numeric", "numeric", "numeric")
  )
summary(motorcycle)
```


```{r, echo=FALSE, fig.width=10, fig.height=4}
# tmp <- lapply(names(motorcycle), function(x) 
#                   ggplot(data = motorcycle[, x, drop = FALSE]) +
#                     aes_string(x) + xlab(x) + ylab(""))
# gd <- geom_density(adjust = 2, fill = gray(.5))
# gh <- geom_bar()
# grid.arrange(
#   tmp[[1]] + gd,
#   tmp[[2]] + gh,
#   tmp[[3]] + gh,
#   tmp[[4]] + gh,
#   tmp[[5]] + gd,
#   tmp[[6]] + gh,
#   tmp[[7]] + gd,
#   tmp[[8]] + gd,
#   tmp[[9]] + gd,
#   ncol = 4
# )

#Only obs with claims also excluding :
    gClaim <- ggplot(data = motorcycle[motorcycle$claims > 0 & motorcycle$age > 15, ])
# Plot showing distribution of ages given that the insurrance has been relevant (claims > 0)
    #ageClaimp <- gClaim + geom_bar(aes(x = age), fill = grey(.7)) + theme_bw() + xlim(c(16, 75))
    #ageClaimp

#Plotting boxplots for the various factor covariates:
pBox1 <- gClaim + geom_boxplot(aes(x = zone, y = cost))
pBox2 <- gClaim + geom_boxplot(aes(x = mcClass, y = cost))
pBox3 <- gClaim + geom_boxplot(aes(x = bonusClass, y = cost))
pBox4 <- gClaim + geom_boxplot(aes(x = gender, y = cost))

grid.arrange(
  pBox1,
  pBox2,
  pBox3,
  pBox4,
  ncol = 4
)
# Hej Niels
g <- ggplot(data = motorcycle)

g + geom_smooth(aes(x = age, y = duration))
gClaim + geom_smooth(aes(x = age, y = duration))


```

